### ISSUE TITLE
При запуске в автоматическом режиме не работают исключения

### ISSUE THREAD

**Issue by RussianFishery** [Tavalik/VA-SmokeTests#2]
При запуске в автоматическом режиме не работают исключения.
Ошибка в модуле форме (строка 115):
		
Если Найти(ЗначениеПараметра, "КаталогФайловИсключений=") Тогда
    ИмяКонфигурацииПоставщика = СокрЛП(СтрЗаменить(ЗначениеПараметра, "КаталогФайловИсключений=", ""));
КонецЕсли;

**Comment by Tavalik** [comment]
Исправлено. Также исправление вошло и в Vanessa-Automation
